# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlatKB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('periode_pemakaian', models.IntegerField(help_text='dalam hari')),
            ],
        ),
        migrations.CreateModel(
            name='KB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai_pemakaian', models.DateField()),
                ('tanggal_kontrol', models.DateField()),
                ('alat_kb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AlatKB')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('biaya', models.IntegerField()),
                ('bidan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_bidan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=30)),
                ('nama', models.CharField(max_length=30)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='kunjungan',
            name='obat',
            field=models.ManyToManyField(to='core.Obat'),
        ),
        migrations.AddField(
            model_name='kunjungan',
            name='pasien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan_pasien', to=settings.AUTH_USER_MODEL),
        ),
    ]
